// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxNyT7G3DWiuQ4oQL8UntSMKZgLsZYTNE',
    appId: '1:608620482557:web:81f62d2f7d61eb21659394',
    messagingSenderId: '608620482557',
    projectId: 'finalexam-30f00',
    authDomain: 'finalexam-30f00.firebaseapp.com',
    storageBucket: 'finalexam-30f00.appspot.com',
    measurementId: 'G-XTFVNCL310',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfUSuCET87pzW15xG695w0fYo8bqr80Eo',
    appId: '1:608620482557:android:01394fb049f9834b659394',
    messagingSenderId: '608620482557',
    projectId: 'finalexam-30f00',
    storageBucket: 'finalexam-30f00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcyPzK4O6i3ivxh6QOXbSwKrXbU2wvpQk',
    appId: '1:608620482557:ios:297c1410b818422d659394',
    messagingSenderId: '608620482557',
    projectId: 'finalexam-30f00',
    storageBucket: 'finalexam-30f00.appspot.com',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcyPzK4O6i3ivxh6QOXbSwKrXbU2wvpQk',
    appId: '1:608620482557:ios:297c1410b818422d659394',
    messagingSenderId: '608620482557',
    projectId: 'finalexam-30f00',
    storageBucket: 'finalexam-30f00.appspot.com',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxNyT7G3DWiuQ4oQL8UntSMKZgLsZYTNE',
    appId: '1:608620482557:web:a93f3c96951cedf4659394',
    messagingSenderId: '608620482557',
    projectId: 'finalexam-30f00',
    authDomain: 'finalexam-30f00.firebaseapp.com',
    storageBucket: 'finalexam-30f00.appspot.com',
    measurementId: 'G-M56HCX9LNJ',
  );
}
